### ISSUE TITLE
Allow support for remembering share path and username

### ISSUE THREAD

**Issue by illiminable** [GoogleChrome/chromeos_network_file_share#43]
For cases where user does not want to save password there should be some UI to at least store the share name and possibly user name so the user does not have to retype it every time they reboot.

**Comment by liltinkerer** [comment]
Is this project dead? @illiminable

**Comment by illiminable** [comment]
No. The project is not dead :) I'm working on several things right now but there will be an update coming in the next few weeks.

**Comment by allenktv** [comment]
Should this be saved under [sync](https://developer.chrome.com/extensions/storage#property-sync) or [local](https://developer.chrome.com/extensions/storage#property-local)?

Also would this automatically happen, or should there be a checkbox or something that the user can toggle?

**Comment by allenktv** [comment]
I see that there is already an option to "store credentials" after selecting the password checkbox. Correct me if I am wrong, but it would seem that we don't need to store username for this issue since there is already that feature.

Currently I thinking that this can just happen automatically, saving us from adding another checkbox (there would be 3 if we did)
