### ISSUE TITLE
"Not Compatible?"

### ISSUE THREAD

**Issue by wfeiereisen** [GoogleChrome/chromeos_network_file_share#55]
I have the original 2011 Samsung Series 5 Chromebook. The webstore displays a red not compatible button. Google searches reveal some hints at 32 bit not being supported. Am I orphaned with this old machine?

**Comment by illiminable** [comment]
Unfortunately as far as this app goes you are for the time being. Since this app uses NaCl there is a cost to both getting the port working and that the app has to carry the binaries for all platforms.

I may try and attempt it at some point but since there are so many more higher priority bugs it likely won't be soon.

**Comment by illiminable** [comment]
Dupe #42
